services: docker
dist: bionic
language: cpp
git:
  depth: false

env:
  - BOOST_VERSION=1.73.0 GCC_VERSION=10.1.0
  - BOOST_VERSION=1.64.0 GCC_VERSION=8.1.0

before_install:
   - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
   - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
   - sudo apt-get update
   - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce

script:
  - docker run --name centos7_bash -v ${TRAVIS_BUILD_DIR}:/mnt/travis_build_dir -it -d kiwabuchi/metall_test:centos7 bash
  - docker exec -it -w /mnt/travis_build_dir -e TRAVIS_BUILD_ID -e BOOST_VERSION -e GCC_VERSION -e TRAVIS_BUILD_NUMBER -e TRAVIS_JOB_NUMBER --env PATH="/var/spack/bin:${PATH}" centos7_bash bash -c '. /var/spack/share/spack/setup-env.sh && spack load boost@${BOOST_VERSION} gcc@${GCC_VERSION} && export METALL_TEST_DIR="/tmp/${TRAVIS_BUILD_NUMBER}-${TRAVIS_JOB_NUMBER}" && export METALL_LIMIT_MAKE_PARALLELS=2 && bash ./scripts/CI/build_and_test.sh'
