services: docker
dist: bionic
language: cpp
git:
  depth: false

env:
  - BOOST_VERSION=1_72_0 CC=gcc8.1.0 CXX=g++8.1.0
  - BOOST_VERSION=1_72_0 CC=gcc8.2.0 CXX=g++8.2.0
#  - BOOST_VERSION=1_72_0 CC=gcc8.3.0 CXX=g++8.3.0
#  - BOOST_VERSION=1_72_0 CC=gcc9.1.0 CXX=g++9.1.0
#  - BOOST_VERSION=1_72_0 CC=gcc9.2.0 CXX=g++9.2.0
#  - BOOST_VERSION=1_71_0 CC=gcc8.1.0 CXX=g++8.1.0
#  - BOOST_VERSION=1_71_0 CC=gcc8.2.0 CXX=g++8.2.0
#  - BOOST_VERSION=1_71_0 CC=gcc8.3.0 CXX=g++8.3.0
#  - BOOST_VERSION=1_71_0 CC=gcc9.1.0 CXX=g++9.1.0
#  - BOOST_VERSION=1_71_0 CC=gcc9.2.0 CXX=g++9.2.0
#  - BOOST_VERSION=1_70_0 CC=gcc8.1.0 CXX=g++8.1.0
#  - BOOST_VERSION=1_70_0 CC=gcc8.2.0 CXX=g++8.2.0
#  - BOOST_VERSION=1_70_0 CC=gcc8.3.0 CXX=g++8.3.0
#  - BOOST_VERSION=1_70_0 CC=gcc9.1.0 CXX=g++9.1.0
#  - BOOST_VERSION=1_70_0 CC=gcc9.2.0 CXX=g++9.2.0
#  - BOOST_VERSION=1_69_0 CC=gcc8.1.0 CXX=g++8.1.0
#  - BOOST_VERSION=1_69_0 CC=gcc8.2.0 CXX=g++8.2.0
#  - BOOST_VERSION=1_69_0 CC=gcc8.3.0 CXX=g++8.3.0
#  - BOOST_VERSION=1_69_0 CC=gcc9.1.0 CXX=g++9.1.0
#  - BOOST_VERSION=1_69_0 CC=gcc9.2.0 CXX=g++9.2.0
#  - BOOST_VERSION=1_68_0 CC=gcc8.1.0 CXX=g++8.1.0
#  - BOOST_VERSION=1_68_0 CC=gcc8.2.0 CXX=g++8.2.0
#  - BOOST_VERSION=1_68_0 CC=gcc8.3.0 CXX=g++8.3.0
#  - BOOST_VERSION=1_68_0 CC=gcc9.1.0 CXX=g++9.1.0
#  - BOOST_VERSION=1_68_0 CC=gcc9.2.0 CXX=g++9.2.0
#  - BOOST_VERSION=1_67_0 CC=gcc8.1.0 CXX=g++8.1.0
#  - BOOST_VERSION=1_67_0 CC=gcc8.2.0 CXX=g++8.2.0
#  - BOOST_VERSION=1_67_0 CC=gcc8.3.0 CXX=g++8.3.0
#  - BOOST_VERSION=1_67_0 CC=gcc9.1.0 CXX=g++9.1.0
#  - BOOST_VERSION=1_67_0 CC=gcc9.2.0 CXX=g++9.2.0
#  - BOOST_VERSION=1_66_0 CC=gcc8.1.0 CXX=g++8.1.0
#  - BOOST_VERSION=1_66_0 CC=gcc8.2.0 CXX=g++8.2.0
#  - BOOST_VERSION=1_66_0 CC=gcc8.3.0 CXX=g++8.3.0
#  - BOOST_VERSION=1_66_0 CC=gcc9.1.0 CXX=g++9.1.0
#  - BOOST_VERSION=1_66_0 CC=gcc9.2.0 CXX=g++9.2.0
#  - BOOST_VERSION=1_65_1 CC=gcc8.1.0 CXX=g++8.1.0
#  - BOOST_VERSION=1_65_1 CC=gcc8.2.0 CXX=g++8.2.0
#  - BOOST_VERSION=1_65_1 CC=gcc8.3.0 CXX=g++8.3.0
#  - BOOST_VERSION=1_65_1 CC=gcc9.1.0 CXX=g++9.1.0
#  - BOOST_VERSION=1_65_1 CC=gcc9.2.0 CXX=g++9.2.0
#  - BOOST_VERSION=1_65_0 CC=gcc8.1.0 CXX=g++8.1.0
#  - BOOST_VERSION=1_65_0 CC=gcc8.2.0 CXX=g++8.2.0
#  - BOOST_VERSION=1_65_0 CC=gcc8.3.0 CXX=g++8.3.0
#  - BOOST_VERSION=1_65_0 CC=gcc9.1.0 CXX=g++9.1.0
#  - BOOST_VERSION=1_65_0 CC=gcc9.2.0 CXX=g++9.2.0
#  - BOOST_VERSION=1_64_0 CC=gcc8.1.0 CXX=g++8.1.0
#  - BOOST_VERSION=1_64_0 CC=gcc8.2.0 CXX=g++8.2.0
#  - BOOST_VERSION=1_64_0 CC=gcc8.3.0 CXX=g++8.3.0
#  - BOOST_VERSION=1_64_0 CC=gcc9.1.0 CXX=g++9.1.0
#  - BOOST_VERSION=1_64_0 CC=gcc9.2.0 CXX=g++9.2.0

before_install:
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce

script:
  - docker run --name centos7_bash -v ${TRAVIS_BUILD_DIR}:/mnt/travis_build_dir -it -d kiwabuchi/metall_test:centos7 bash
  - docker exec -it -w /mnt/travis_build_dir -e CC -e CXX --env CMAKE_PREFIX_PATH="${CMAKE_PREFIX_PATH}:/var/boost/boost_${BOOST_VERSION}" centos7_bash bash ./scripts/CI/build_and_test.sh
