
site_name: Metall
site_author: 'Keita Iwabuchi (LLNL), Roger A Pearce (LLNL), and Maya B Gokhale (LLNL)'
copyright: Copyright 2020 Lawrence Livermore National Security, LLC

docs_dir: 'docs/readthedocs'
theme: 'readthedocs'
extra_css:
  - ./css/custom.css

repo_url: https://github.com/LLNL/metall
edit_uri: 'tree/develop/docs/readthedocs'

nav:
- 'HOME': 'index.md'
- 'BASICS':
  - 'Getting Started': 'basics/getting_started.md'
  - 'Compile-time Options': 'basics/compile_time_options.md'
- 'ADVANCED BUILD':
  - 'Build Executables': 'advanced_build/cmake.md'
  - 'Use Umap': 'advanced_build/umap.md'
  - 'Test Metall': 'advanced_build/test.md'
- 'Metall 101':
  - 'Introduction': 'detail/introduction.md'
  - 'API': 'detail/api.md'
  - 'Data Store ls': 'detail/ls.md'
  - 'Pointers in Persistent Memory': 'detail/pointer.md'
  - 'Persistence Policy': 'detail/persistence_policy.md'
  - 'Snapshot': 'detail/snapshot.md'
  - 'Example': 'detail/example.md'
  - 'Internal Architecture': 'detail/internal_architecture.md'
- 'ABOUT':
  - 'License and Notice': 'about/license_notice.md'
