function(metall_add_build_interface_include_dirs target_name)
  foreach(include_dir IN LISTS ARGN)
    if(include_dir)
      target_include_directories(${target_name} INTERFACE $<BUILD_INTERFACE:${include_dir}>)
    endif()
  endforeach()
endfunction()

function(metall_add_build_interface_compile_definitions target_name)
  foreach(compile_definition IN LISTS ARGN)
    if(compile_definition)
      target_compile_definitions(${target_name} INTERFACE $<BUILD_INTERFACE:${compile_definition}>)
    endif()
  endforeach()
endfunction()

function(metall_resolve_target_name output_var target_name)
  if(TARGET ${target_name})
    get_target_property(aliased_target ${target_name} ALIASED_TARGET)
    if(aliased_target)
      set(${output_var} ${aliased_target} PARENT_SCOPE)
    else()
      set(${output_var} ${target_name} PARENT_SCOPE)
    endif()
  else()
    set(${output_var} ${target_name} PARENT_SCOPE)
  endif()
endfunction()

function(metall_convert_local_targets_to_link_items output_var)
  set(link_items "")
  foreach(link_item IN LISTS ARGN)
    if(TARGET ${link_item})
      metall_resolve_target_name(target_to_check ${link_item})

      get_target_property(link_item_imported ${target_to_check} IMPORTED)
      get_target_property(link_item_type ${target_to_check} TYPE)
      if(link_item_imported)
        list(APPEND link_items ${link_item})
      elseif(link_item_type STREQUAL "INTERFACE_LIBRARY")
        continue()
      else()
        list(APPEND link_items "$<TARGET_LINKER_FILE:${target_to_check}>")
      endif()
    else()
      list(APPEND link_items ${link_item})
    endif()
  endforeach()
  set(${output_var} ${link_items} PARENT_SCOPE)
endfunction()

function(metall_collect_local_target_dependencies output_var)
  set(local_target_dependencies "")
  foreach(link_item IN LISTS ARGN)
    if(TARGET ${link_item})
      metall_resolve_target_name(target_to_check ${link_item})

      get_target_property(link_item_imported ${target_to_check} IMPORTED)
      get_target_property(link_item_type ${target_to_check} TYPE)
      if(NOT link_item_imported AND NOT link_item_type STREQUAL "INTERFACE_LIBRARY")
        list(APPEND local_target_dependencies ${target_to_check})
      endif()
    endif()
  endforeach()
  list(REMOVE_DUPLICATES local_target_dependencies)
  set(${output_var} ${local_target_dependencies} PARENT_SCOPE)
endfunction()

function(metall_collect_target_interface_property output_var property_name)
  set(collected_values "")
  foreach(link_item IN LISTS ARGN)
    if(TARGET ${link_item})
      metall_resolve_target_name(target_to_check ${link_item})

      get_target_property(property_values ${target_to_check} ${property_name})
      if(property_values AND NOT property_values STREQUAL "${property_name}-NOTFOUND")
        list(APPEND collected_values ${property_values})
      endif()
    endif()
  endforeach()
  list(REMOVE_DUPLICATES collected_values)
  set(${output_var} ${collected_values} PARENT_SCOPE)
endfunction()

function(metall_mirror_target_usage_to_build_interface target_name)
  metall_collect_target_interface_property(interface_include_dirs INTERFACE_INCLUDE_DIRECTORIES ${ARGN})
  metall_collect_target_interface_property(interface_compile_definitions INTERFACE_COMPILE_DEFINITIONS ${ARGN})
  metall_add_build_interface_include_dirs(${target_name} ${interface_include_dirs})
  metall_add_build_interface_compile_definitions(${target_name} ${interface_compile_definitions})
endfunction()

function(metall_link_build_local_targets target_name visibility)
  if(CMAKE_VERSION VERSION_GREATER_EQUAL "3.26")
    foreach(link_item IN LISTS ARGN)
      if(link_item)
        target_link_libraries(${target_name} ${visibility}
          "$<BUILD_LOCAL_INTERFACE:${link_item}>")
      endif()
    endforeach()
  else()
    metall_convert_local_targets_to_link_items(export_safe_link_items ${ARGN})
    if(export_safe_link_items)
      target_link_libraries(${target_name} ${visibility} ${export_safe_link_items})
    endif()
  endif()
endfunction()
