function(add_gcc_preprocessor_definition name)
    if (${CMAKE_VERSION} VERSION_LESS "3.12.0")
        add_compile_definitions(name)
    else()
        add_definitions(-D${name})
    endif ()
endfunction()