name: CI Test

on: [push, pull_request]

jobs:
  bst1-87-0:
    runs-on: ubuntu-latest
    env:
      METALL_LIMIT_MAKE_PARALLELS: 8
    steps:
      - uses: actions/checkout@v3
      - name: Test
        run: |
          pushd /dev/shm
          wget -q https://archives.boost.io/release/1.87.0/source/boost_1_87_0.tar.gz
          mkdir boost
          tar xf boost_1_87_0.tar.gz -C boost --strip-components 1
          export BOOST_ROOT=${PWD}/boost
          popd
          export METALL_TEST_DIR=${GITHUB_JOB}
          export CC=gcc-12
          export CXX=g++-12
          cd $GITHUB_WORKSPACE
          bash ./scripts/CI/build_and_test.sh

  bst1-80-0:
    runs-on: ubuntu-latest
    env:
      METALL_LIMIT_MAKE_PARALLELS: 8
    steps:
      - uses: actions/checkout@v3
      - name: Test
        run: |
          pushd /dev/shm
          wget -q https://archives.boost.io/release/1.80.0/source/boost_1_80_0.tar.gz
          mkdir boost
          tar xf boost_1_80_0.tar.gz -C boost --strip-components 1
          export BOOST_ROOT=${PWD}/boost
          popd
          export METALL_TEST_DIR=${GITHUB_JOB}
          export CC=gcc-12
          export CXX=g++-12
          cd $GITHUB_WORKSPACE
          bash ./scripts/CI/build_and_test.sh
