name: Deploy API Doc

on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Generate
        run: |
          sudo apt-get install doxygen
          mkdir build_doc
          cd build_doc
          doxygen ../docs/Doxyfile.in
          mkdir -p ../public/api
          cp -r ./html/* ../public/api/
          cd ../

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public